/**
 * Generates the `tmux` PATH shim that keeps each Argus pane on its own view of
 * a shared tmux session.
 *
 * Clients attached to one tmux session share that session's current window, so
 * two panes attaching to the same session mirror each other keystroke for
 * keystroke. A grouped session (`new-session -t <base>`) shares the window list
 * but keeps its own current window — one pane's worth of view.
 */

/** Marks a session as an Argus-owned view; views are never isolated again. */
export const TMUX_VIEW_SESSION_MARKER = '@orca-'

/** Set to `off` in a pane's env to hand tmux back untouched. */
export const TMUX_SESSION_ISOLATION_OPT_OUT_ENV = 'ORCA_TMUX_SESSION_ISOLATION'

export function buildTmuxSessionIsolationShim(realTmuxPath: string): string {
  return `#!/usr/bin/env sh
# Generated by Argus. Keeps each pane on its own view of a shared tmux session.
set -u

real="\${ORCA_REAL_TMUX:-${realTmuxPath}}"
VIEW_MARKER='${TMUX_VIEW_SESSION_MARKER}'

if [ ! -x "$real" ]; then
  # Never fall back to bare \`tmux\`: PATH resolves that back to this shim.
  self="\${ORCA_TMUX_SHIM_DIR:-$(dirname -- "$0")}"
  clean='' rest="\${PATH}:"
  while [ -n "$rest" ]; do
    dir="\${rest%%:*}"
    rest="\${rest#*:}"
    [ "$dir" = "$self" ] && continue
    clean="\${clean:+$clean:}$dir"
  done
  PATH="$clean"
  export PATH
  exec tmux "$@"
fi

# Claude's agent teams replace tmux with an emulator over Argus panes. Hand off
# rather than relying on PATH order, which a user's rc file can reshuffle.
if [ -n "\${ORCA_AGENT_TEAMS_SHIM_DIR:-}" ] && [ -x "\${ORCA_AGENT_TEAMS_SHIM_DIR}/tmux" ]; then
  exec "\${ORCA_AGENT_TEAMS_SHIM_DIR}/tmux" "$@"
fi

# Inert outside an Argus pane, when nesting inside tmux, or when opted out.
if [ -z "\${ORCA_PANE_KEY:-}" ] || [ -n "\${TMUX:-}" ] ||
  [ "\${${TMUX_SESSION_ISOLATION_OPT_OUT_ENV}:-on}" = 'off' ]; then
  exec "$real" "$@"
fi

tmux_at() {
  _l="$1" _s="$2"
  shift 2
  if [ -n "$_l" ]; then
    "$real" -L "$_l" "$@"
  elif [ -n "$_s" ]; then
    "$real" -S "$_s" "$@"
  else
    "$real" "$@"
  fi
}

# Prints "sockL<TAB>sockS<TAB>base<TAB>flags" when this invocation should be
# isolated, nothing when it should reach tmux untouched.
scan_plan() {
  sock_l='' sock_s='' cmd='' target_t='' target_s='' flags=''
  exclusive=no detached=no attach_if_exists=no

  while [ $# -gt 0 ]; do
    case "$1" in
      -L) sock_l="\${2:-}"; shift 2 || return 0 ;;
      -L*) sock_l="\${1#-L}"; shift ;;
      -S) sock_s="\${2:-}"; shift 2 || return 0 ;;
      -S*) sock_s="\${1#-S}"; shift ;;
      -c | -f | -T) shift 2 || return 0 ;;
      -c* | -f* | -T*) shift ;;
      --) shift; break ;;
      -*) shift ;;
      *) break ;;
    esac
  done
  [ $# -gt 0 ] || return 0
  cmd="$1"
  shift

  case "$cmd" in
    # tmux accepts any unambiguous prefix; \`a\` onward is unambiguous here.
    a | at | att | atta | attac | attach | attach-session) : ;;
    new | new-session) attach_if_exists=yes ;;
    *) return 0 ;;
  esac

  while [ $# -gt 0 ]; do
    case "$1" in
      -t) target_t="\${2:-}"; shift 2 || return 0 ;;
      -t*) target_t="\${1#-t}"; shift ;;
      -s) target_s="\${2:-}"; shift 2 || return 0 ;;
      -s*) target_s="\${1#-s}"; shift ;;
      -c | -e | -f | -n | -x | -y | -F) shift 2 || return 0 ;;
      -d) detached=yes; shift ;;
      -D | -X) exclusive=yes; shift ;;
      -A) attach_if_exists=confirmed; shift ;;
      -r) flags="$flags -r"; shift ;;
      -E) flags="$flags -E"; shift ;;
      --) shift; break ;;
      -*) shift ;;
      *) break ;;
    esac
  done

  # -d/-D/-X all say "this client takes the session over"; that beats isolation.
  [ "$exclusive" = no ] || return 0
  [ "$detached" = no ] || return 0
  # new-session without -A builds a session nobody else can already be on.
  [ "$attach_if_exists" != yes ] || return 0

  # new-session names its session with -s; its -t is the group it joins.
  if [ "$attach_if_exists" = confirmed ]; then
    target="$target_s"
  else
    target="$target_t"
  fi
  base="\${target%%:*}"
  base="\${base#=}"
  case "$base" in *"$VIEW_MARKER"*) return 0 ;; esac

  if [ -n "$base" ]; then
    tmux_at "$sock_l" "$sock_s" has-session -t "=$base" 2>/dev/null || return 0
  else
    base="$(tmux_at "$sock_l" "$sock_s" list-sessions \\
      -F '#{session_activity} #{session_name}' 2>/dev/null |
      sort -rn | sed -n '1s/^[0-9]* //p')"
    [ -n "$base" ] || return 0
    case "$base" in *"$VIEW_MARKER"*) return 0 ;; esac
  fi

  printf '%s\\t%s\\t%s\\t%s\\n' "$sock_l" "$sock_s" "$base" "$flags"
}

plan="$(scan_plan "$@")" || plan=''
[ -n "$plan" ] || exec "$real" "$@"

sock_l="\${plan%%	*}"
rest="\${plan#*	}"
sock_s="\${rest%%	*}"
rest="\${rest#*	}"
base="\${rest%%	*}"
flags="\${rest#*	}"

rt() { tmux_at "$sock_l" "$sock_s" "$@"; }

# One view per pane, stable across relaunches so a pane returns to the window it
# left behind. The pane key's leaf id is a UUID; its tail is the entropy.
digest="$(printf '%s' "\${ORCA_PANE_KEY##*:}" | tr -cd 'a-zA-Z0-9' | tail -c 12)"
[ -n "$digest" ] || digest="$(printf '%s' "$ORCA_PANE_KEY" | cksum | cut -d' ' -f1)"
view="\${base}\${VIEW_MARKER}\${digest}"

if ! rt has-session -t "=$view" 2>/dev/null; then
  rt new-session -d -s "$view" -t "=$base" 2>/dev/null || exec "$real" "$@"
fi

# Attaching means "show me where this session is now"; the view buys
# independence between attaches, not across them.
active="$(rt list-windows -t "=$base" -F '#{window_active} #{window_id}' 2>/dev/null |
  sed -n 's/^1 //p')"
[ -z "$active" ] || rt select-window -t "=\${view}:\${active}" 2>/dev/null || true

# A pane killed without detaching would strand its view. destroy-unattached
# collects it, but arming it before this attach lands would reap the view first.
# Arming once the wait is up covers the pane that died inside that window.
nap() { sleep 0.2 2>/dev/null || sleep 1; }
(
  n=0
  while [ "$n" -lt 40 ]; do
    [ -z "$(rt list-clients -t "=$view" -F 'x' 2>/dev/null)" ] || break
    nap
    n=$((n + 1))
  done
  # The trailing colon forces session scope: set-option takes a pane target.
  rt set-option -t "=\${view}:" destroy-unattached on 2>/dev/null
) &

set --
[ -z "$sock_l" ] || set -- "$@" -L "$sock_l"
[ -z "$sock_s" ] || set -- "$@" -S "$sock_s"
set -- "$@" attach-session -t "=$view" $flags
"$real" "$@"
status=$?
rt kill-session -t "=$view" 2>/dev/null || true
exit "$status"
`
}
